### PR TITLE
change by_class to by.class in caret_tidiers

### PR DESCRIPTION
**Pull request by sushmitavgopalan16**
this is in response to issue #750

### CODE REVIEW

**Comment by IndrajeetPatil** [comment]
You also need to change the tests to reflect the change in the argument name from `by_class` to `by.class`.

**Comment by IndrajeetPatil** [comment]
Thanks. The tests are still failing for some reason though:
https://ci.appveyor.com/project/alexpghayes/broom/builds/27379757/job/94hk668iuby0wfn8

Are they passing locally for you?

**Comment by alexpghayes** [comment]
Probably needs a change in `modeltests`. I'll take care of that. In the meantime, @sushmitavgopalan16 can you:

- [ ] add yourself as a contributor in `DESCRIPTION`
- [ ] update `NEWS` describing the change you've made

**Comment by sushmitavgopalan16** [comment]
Thanks @alexpghayes! just made the changes!

**Comment by simonpcouch** [comment]
Closing per discussion in #750--thanks for your contribution. :-)

**Pull request closed without merging**
