### PR TITLE
handle `.resid` in `augment` output when response includes function calls

### LINKED ISSUE #1121: Missing .resid when terms in the formula are function calls
This is a request to reopen #124 , with a potential diagnosis and fix.
This bug describes how the .resid column is missing when terms in the formula are function calls of variables, eg. `log(var)`.

I believe the problem is in the response function in utilities.R; it attempts to create the response variable by calling `model.response` on a new version of the data set, created using `model.frame(terms(object), data = newdata)`. The problem with this is that if `newdata` was created using `model.frame` in the first place (which it is by default in `augment_newdata`), it will already have the results from the function calls instead of the data itself, so recreating the function calls fails.

The solution is to check if newdata already has a response (ie, was created from `model.frame`), and if so, to use that directly, instead of recreating it. If not, then the current code should be run. The below code adds this, wrapping it in a `possibly`, as if it doesn't have a response associated with it, an error is likely.

See ?model.frame/?get_all_vars (the last paragraph of Details) for a brief explanation of what `model.frame` does, in contrast with with `get_all_vars` does. I don't think we can't use `get_all_vars` instead because it requires the raw data set as a parameter.

```
response <- function(object, newdata = NULL) {
  ## if the newdata was created as a model.frame, it will have a response already
  ## wrap this in possibly, because if not, an error is likely
  safe_model.response <- purrr::possibly(model.response, NULL)
  resp <- safe_model.response(newdata)
  ## if not, need to recreate it from the newdata
  if(is.null(resp)) {
    resp <- model.response(model.frame(terms(object), data = newdata, na.action = na.pass))
  }
  resp
}
```

### PR DESCRIPTION
**Pull request by simonpcouch**
Closes #1121, related to #946, #937, #124.🐬

### CODE REVIEW

**Comment by simonpcouch** [comment]
Would you be able to take a look at this, @alexpghayes? You mentioned some edge cases to be wary of in #1121, so wanted to give you a chance to see this before merging.

**Comment by alexpghayes** [comment]
Yes, I'll take a look by the end of the week.

**Comment by alexpghayes** [comment]
I just took a look and this seems fine to me! I don't really remember the implementation details as well as I would like, but I find the tests convincing :).

**Review by alexpghayes — APPROVED** [review]

**Comment by simonpcouch** [comment]
Much appreciated, @alexpghayes!

**Pull request merged**
