### PR TITLE
add new renamers in tidy.anova to comply with Anova:::car.coxph

### LINKED ISSUE #754: tidy.anova car:::Anova.coxph new renamer
The p-value renamer for tidy.anova lacks `Pr(>|Chi|)` which is returned by `car:::Anova.coxph`.

```r
library(survival)
mod <- coxph(Surv(time, status) ~ differ, data = colon)
car::Anova(mod) %>% tidy()
```

### PR DESCRIPTION
**Pull request by KZARCA**
fix #754

### CODE REVIEW

**Comment by alexpghayes** [comment]
Can you:

- [ ] add a test, and 
- [ ] update news

and then I'll merge!

**Comment by KZARCA** [comment]
Hi @alexpghayes,
I added the test and updated NEWS in the PR.
Best

**Comment by alexpghayes** [comment]
Great! Are you listed in the `DESCRIPTION` as a contributor? If not, please add yourself! Otherwise I'll merge!

**Comment by KZARCA** [comment]
Done! Thank you very much for that! I really appreciate!

**Pull request merged**
