### PR TITLE
Added tidiers for drc

### PR DESCRIPTION
**Pull request by EDiLD**
Added tidiers for [drc](https://cran.r-project.org/web/packages/drc/index.html), which provides a big variety of dose-response-models.

Example: 
```r
 library(drc)
 mod <- drm(dead/total~conc, type, 
    weights = total, data = selenium, fct = LL.2(), type = "binomial")
 mod
 
 tidy(mod)
 tidy(mod, conf.int = TRUE)
 tidy(mod, quick = TRUE)

 glance(mod)
```

I really had to fight with the tests for `augment()`, but I could not get them pass :(. Code is in here, but uncommented. If someone more experienced with broom might want to look into it. 

Failing tests are unrelated to this PR.

### CODE REVIEW

**Comment by alexpghayes** [comment]
Thanks! I'll take a look at the augment method in a couple days!

**Comment by EDiLD** [comment]
@alexpghayes I fixed also the augment.drc() part - so no need for you to check.
I still need make a small fix to modeltest, before this ready

**Comment by EDiLD** [comment]
@alexpghayes  If you have any suggestions/comments we could have also a chat in person at rstudio::conf (I am participating in the ML workshop).

**Comment by EDiLD** [comment]
Getting some

> Arguments conf.int, conf.level to `augment.drc` must be listed in the argument glossary.

errors, when testing. Although I do inline definition of columns

```
return_augment(".conf.low" = "Lower Confidence Interval",
[snip]
```

Any idea?

**Comment by alexpghayes** [comment]
Yes, let's chat in person! Just flag me down!

**Comment by alexpghayes** [comment]
I'm sorry that I haven't look at this yet. I'll try to give this a thorough review over the weekend!

**Comment by alexpghayes** [comment]
I'm sorry for the delay on this! I'm going to go ahead and merge and poke through the code as I have time!

**Pull request merged**
