### PR TITLE
Update stats-htest-tidiers.R

### PR DESCRIPTION
**Pull request by rsbivand**
Check whether ret$estimate is named before assigning names, if named do not overwrite names (similar logic to checking for parameter names in the same method).

### CODE REVIEW

**Comment by rsbivand** [comment]
@alexpghayes Please motivate your rejection - I do not know of, or was asked about, the unnumbered issue to which you refer.

**Comment by alexpghayes** [comment]
Right. Apologies for the hasty decision making -- I've been try to cram a lot of maintenance into a short time period. Two relevant issues are #31 and #115. Revisiting #115 it looks like we only partially came to a conclusion on what to do and then the implementation got absorbed in the #326, which is a behemoth PR that needs a lot of work.

The main concern I recall with informative names for the means was that it would make `map*`-ing difficult. One option is to add an argument that controls whether you get group names or `estimate1` and `estimate2` , and default to group names. What do you think about this?

**Comment by rsbivand** [comment]
Thanks for getting back to me. I am not convinced by map/group arguments, and without a reprex say using one of the following standard tests would find it hard to think of a relevant context. By dropping names added for good reasons by function authors, potentially important information is lost, I think.

Some (legacy) examples of named estimate components of htest objects - most of these have meaningful names, often recording how the test was applied:

```
library(stats)
names(ansari.test(rnorm(10), rnorm(10, 0, 2), conf.int = TRUE)$estimate)
names(binom.test(c(682, 243), p = 3/4)$estimate)
names(cor.test(rnorm(5), rnorm(5), method = "kendall", alternative = "greater")$estimate)
TeaTasting <- matrix(c(3, 1, 1, 3),  nrow = 2, dimnames = list(Guess = c("Milk", "Tea"), Truth = c("Milk", "Tea")))
names(fisher.test(TeaTasting, alternative = "greater")$estimate)
Rabbits <- array(c(0, 0, 6, 5, 3, 0, 3, 6, 6, 2, 0, 4, 5, 6, 1, 0, 2, 5, 0, 0), dim = c(2, 2, 5),        dimnames = list(Delay = c("None", "1.5h"), Response = c("Cured", "Died"), Penicillin.Level = c("1/8", "1/4", "1/2", "1", "4")))
names(mantelhaen.test(Rabbits)$estimate)
names(poisson.test(137, 24.19893)$estimate)
smokers  <- c( 83, 90, 129, 70 )
patients <- c( 86, 93, 136, 82 )
names(prop.test(smokers, patients)$estimate)
names(t.test(extra ~ group, data = sleep)$estimate)
x <- rnorm(50, mean = 0, sd = 2)
y <- rnorm(30, mean = 1, sd = 1)
names(var.test(x, y)$estimate)
x <- c(1.83,  0.50,  1.62,  2.48, 1.68, 1.88, 1.55, 3.06, 1.30)
y <- c(0.878, 0.647, 0.598, 2.05, 1.06, 1.29, 1.06, 3.14, 1.29)
names(wilcox.test(x, y, paired = TRUE, alternative = "greater", conf.int=TRUE)$estimate)
```

**Comment by alexpghayes** [comment]
Cycling back to this. Apologies for the uncommunicative reversion. I believe that this PR ended up breaking something that I reverted in a last minute fix for CRAN. My lack of responsiveness here is a largely a function of my limited capacity for maintenance. I do agree that this is a good idea and also that the former goal of preserving the ability to `map` isn't that important. 

I think a good next step here would be to make re-institute this change and run `revdepcheck`, since I vaguely recall that's where issues emerged last time. I can put this on my own todo list and it will happen eventually, but a new PR with `revdepcheck` results would speed things up if you're looking for this functionality faster.

**Pull request merged**
