### PR TITLE
speedglm p.value

### PR DESCRIPTION
**Pull request by vincentarelbundock**
﻿This PR fixes Issue https://github.com/tidymodels/broom/issues/879

The problem was that, for some reasons, `speedglm` saves p values as a pre-formatted character vector with significance stars built-in. So we have to calculate numeric p values manually.

In the example below, the results with `tidy` and `summary` are identical. I also checked the code for `summary.speedglm`, and it looks like the correct calculation.

``` r
library(speedglm)
library(broom)

x <- seq(1:100)
y <- 3.*x + rnorm(100)*3 + 5.
z <- sample(c('Young','Middle','Old'),100,replace=TRUE)
mod <- speedglm(y~x+z)

tidy(mod)
#> # A tibble: 4 x 5
#>   term        estimate std.error statistic   p.value
#>   <chr>          <dbl>     <dbl>     <dbl>     <dbl>
#> 1 (Intercept)    4.17    0.690       6.05  2.77e-  8
#> 2 x              3.01    0.00997   302.    1.03e-144
#> 3 zOld           0.290   0.691       0.419 6.76e-  1
#> 4 zYoung        -0.360   0.758      -0.475 6.36e-  1

summary(mod)
#> Generalized Linear Model of class 'speedglm':
#> 
#> Call:  speedglm(formula = y ~ x + z) 
#> 
#> Coefficients:
#>  ------------------------------------------------------------------ 
#>             Estimate Std. Error  t value  Pr(>|t|)    
#> (Intercept)   4.1732   0.689634   6.0513  2.77e-08 ***
#> x             3.0056   0.009965 301.6035 1.03e-144 ***
#> zOld          0.2896   0.691116   0.4191  6.76e-01    
#> zYoung       -0.3601   0.757682  -0.4752  6.36e-01    
#> 
#> ------------------------------------------------------------------- 
#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1 
#> 
#> ---
#> null df: 99; null deviance: 753727.9;
#> residuals df: 96; residuals deviance: 778.69;
#> # obs.: 100; # non-zero weighted obs.: 100;
#> AIC: 499.0319; log Likelihood: -244.5159;
#> RSS: 778.7; dispersion: 8.111344; iterations: 1;
#> rank: 4; max tolerance: 1e+00; convergence: FALSE.
```

<sup>Created on 2020-06-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

### CODE REVIEW

**Comment by vincentarelbundock** [comment]
The tests fail because an unrelated issue with `fixest`:

```
-- 2. Error: all other fixest estimators run (@test-fixest.R#108)  -------------
in residuals.fixest(x, type = type.predict...:
 Argument 'type' must be a single character equal to 'response',
'deviance', 'pearson' or 'working'. Problem: no match was found for
'link'.
Backtrace:
 1. modeltests::check_augment_function(...)
 2. broom:::aug(model, newdata = newdata)
 4. fixest:::residuals.fixest(x, type = type.predict, newdata = newdata)
 5. dreamerr::check_arg_plus(type, "match")
 6. dreamerr:::check_arg_core(...)
 7. dreamerr:::send_error(...)
```

It looks like @gregmacfarlane 's recent mlogit PR (https://github.com/tidymodels/broom/pull/887) also fails because of this issue.

@karldw do you think that your https://github.com/tidymodels/broom/pull/877 PR will fix this? If so, it would be nice to merge it, otherwise every single new PR will look broken.

**Comment by karldw** [comment]
@vincentarelbundock, yes, exactly. Sorry the bug in my original fixest PR is causing trouble for everyone else!

**Comment by vincentarelbundock** [comment]
Thanks for the response @karldw , and no worries at all. I'm just glad to know we found the problem!!

**Comment by simonpcouch** [comment]
Hi yall! Thanks for your patience.

This should fixed on the `0.7.0rc` branch and will be merged into master once we manage to get 0.7.0 on CRAN. I'll come back to this once we're able to make that happen and will merge in any changes we had yet to make in fixing that bug. :-)

**Comment by simonpcouch** [comment]
Also dropped a note in #879, but copying here:

I believe this was fixed during the 0.7.0 release process. Could you give this a shot on the `master` branch with the most recent CRAN speedglm version and let me know if you're still getting this result?

**Comment by vincentarelbundock** [comment]
Thanks for looking, but I don't think the problem is fixed. See a reprex and `sessionInfo` below.  The problem is in this line:

https://github.com/tidymodels/broom/blob/master/R/speedglm-speedglm-tidiers.R#L35

There, `broom` converts factor levels to numeric values with a simple call to `as.numeric`. Unfortunately, sometimes the factor levels are hard-coded with asterisks. So master `broom` will extract the correct p.value whenever none of the coefficients are signicant, but not when they are significant.

In this PR, I calculate p.values manually from `statistic`, using code analogous to what `summary.speedglm` uses.

``` r
library(speedglm)
library(broom)

x <- seq(1:100)
y <- 3.*x + rnorm(100)*3 + 5.
z <- sample(c('Young','Middle','Old'),100,replace=TRUE)
mod <- speedglm(y~x+z)
tidy(mod)
#> # A tibble: 4 x 5
#>   term        estimate std.error statistic p.value
#>   <chr>          <dbl>     <dbl>     <dbl>   <dbl>
#> 1 (Intercept)    4.84     0.699      6.91       NA
#> 2 x              2.99     0.0105   286.         NA
#> 3 zOld           1.30     0.815      1.60       NA
#> 4 zYoung         0.324    0.689      0.470      NA
```

```r
> sessionInfo()
R version 4.0.0 (2020-04-24)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.5

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] speedglm_0.3-2   MASS_7.3-51.6    Matrix_1.2-18    broom_0.7.0.9001

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.5       pillar_1.4.6     compiler_4.0.0   remotes_2.1.1    tools_4.0.0     
 [6] digest_0.6.25    evaluate_0.14    lifecycle_0.2.0  tibble_3.0.3     lattice_0.20-41 
[11] pkgconfig_2.0.3  rlang_0.4.7      reprex_0.3.0     rstudioapi_0.11  curl_4.3        
[16] xfun_0.15        dplyr_1.0.0      knitr_1.29       generics_0.0.2   fs_1.4.2        
[21] vctrs_0.3.1      grid_4.0.0       tidyselect_1.1.0 glue_1.4.1       R6_2.4.1        
[26] processx_3.4.3   rmarkdown_2.3    callr_3.4.3      purrr_0.3.4      tidyr_1.1.0     
[31] clipr_0.7.0      magrittr_1.5     whisker_0.4      backports_1.1.8  ps_1.3.3        
[36] ellipsis_0.3.1   htmltools_0.5.0  crayon_1.3.4   
```
<sup>Created on 2020-07-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by simonpcouch** [comment]
So strange. My output with the same reprex (+ a `set.seed`):

``` r
library(speedglm)
#> Loading required package: Matrix
#> Loading required package: MASS
library(broom)

set.seed(1)

x <- seq(1:100)
y <- 3.*x + rnorm(100)*3 + 5.
z <- sample(c('Young','Middle','Old'),100,replace=TRUE)
mod <- speedglm(y~x+z)
tidy(mod)
#> # A tibble: 4 x 5
#>   term        estimate std.error statistic   p.value
#>   <chr>          <dbl>     <dbl>     <dbl>     <dbl>
#> 1 (Intercept)    5.43    0.656       8.28  7.24e- 13
#> 2 x              3.00    0.00949   316.    1.12e-146
#> 3 zOld           0.151   0.712       0.212 8.33e-  1
#> 4 zYoung        -0.241   0.639      -0.378 7.07e-  1

sessionInfo()
#> R version 3.6.3 (2020-02-29)
#> Platform: x86_64-apple-darwin15.6.0 (64-bit)
#> Running under: macOS Catalina 10.15.4
#> 
#> Matrix products: default
#> BLAS:   /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRblas.0.dylib
#> LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib
#> 
#> locale:
#> [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#> [1] broom_0.7.0.9001 speedglm_0.3-2   MASS_7.3-51.4    Matrix_1.2-18   
#> 
#> loaded via a namespace (and not attached):
#>  [1] Rcpp_1.0.5        pillar_1.4.6      compiler_3.6.3    highr_0.8        
#>  [5] tools_3.6.3       digest_0.6.25     evaluate_0.14     lifecycle_0.2.0  
#>  [9] tibble_3.0.3      lattice_0.20-38   pkgconfig_2.0.3   rlang_0.4.7      
#> [13] reprex_0.3.0.9001 cli_2.0.2         rstudioapi_0.11   yaml_2.2.1       
#> [17] xfun_0.15         styler_1.3.2      stringr_1.4.0     dplyr_1.0.0.9000 
#> [21] knitr_1.29        generics_0.0.2    fs_1.4.2          vctrs_0.3.1.9000 
#> [25] grid_3.6.3        tidyselect_1.1.0  glue_1.4.1        R6_2.4.1         
#> [29] fansi_0.4.1       rmarkdown_2.3     purrr_0.3.4       tidyr_1.1.0      
#> [33] magrittr_1.5      backports_1.1.8   ellipsis_0.3.1    htmltools_0.5.0  
#> [37] assertthat_0.2.1  utf8_1.1.4        stringi_1.4.6     crayon_1.3.4.9000
```

<sup>Created on 2020-07-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>


From what I can tell, the asterisks [only appear in the print method](https://github.com/MarcoEnea/speedglm/blob/master/R/summary.speedglm.r#L82-L110) of the speedglm summary. @alexpghayes, can you reproduce this? Any thoughts? Here's the raw reprex code:

```
reprex::reprex({
  library(speedglm)
  library(broom)
  
  x <- seq(1:100)
  y <- 3.*x + rnorm(100)*3 + 5.
  z <- sample(c('Young','Middle','Old'),100,replace=TRUE)
  mod <- speedglm(y~x+z)
  tidy(mod)
  
  sessionInfo()
})
```

**Comment by vincentarelbundock** [comment]
Wow, you're right: super weird.

Could this be a `stringsAsFactors` issue? I see that you are using 3.6.3, and the default to `FALSE` in 4.0.0.

When I run this code, the `p.value` column shows up as character, so the `levels` call produces `NA`:

```r
library(speedglm)
library(broom)

x <- seq(1:100)
y <- 3.*x + rnorm(100)*3 + 5.
z <- sample(c('Young','Middle','Old'),100,replace=TRUE)
x <- speedglm(y~x+z)

ret <- as_tibble(coef(summary(x)), rownames = "term")
colnames(ret) <- c("term", "estimate", "std.error", "statistic", "p.value")

as.numeric(levels(ret$p.value))[ret$p.value]

as.numeric(ret$p.value)
```

Incidentally, if the asterisks are only added by `print`, this PR's mechanism for calculating p values is unnecessarily convoluted. But it could also mean that we need different methods for R>4.0.0

**Comment by simonpcouch** [comment]
Hey @MarcoEnea! Do you have any thoughts on where this issue might be coming up?

**Comment by vincentarelbundock** [comment]
While we're paging @MarcoEnea, I think the fundamental problem here is that in the `speedglm` package, string formatting should be done in the `print.summary.speedglm` method and *not* in the `summary.speedglm` method. That way, p values would be stored as a numeric value in the summary object, and `tidy` could extract it without problem.

I opened an issue here: https://github.com/MarcoEnea/speedglm/issues/2

**Comment by MarcoEnea** [comment]
Hi,
I’ll change it as soon as possible. 

Marco

**Comment by simonpcouch** [comment]
Much appreciated! Closing for now, but let us know if this ends up being a broom issue.

**Pull request closed without merging**
