### PR TITLE
(Issue #1023) tidy.crr take log(CI) when exponentiate = F

### PR DESCRIPTION
**Pull request by leejasme**
PR to fix issue #1023 : the confidence intervals for tidy.crr() which displays exponentiated CI when `exponentiate = F`

- summary.crr provides exponentiated CI 
- changed the default to show the log(CI) from summary.crr instead to match the default of `exponentiate = F`

### CODE REVIEW

**Comment by alexpghayes** [comment]
Given the estimate is named `estimate_exp()` it seems like we're suggesting via the column name that the estimate is always exponentiated. Is this reasonable for these models?

If we make exponentiation optional (see also: the exponentiation idiom), then we should change the column names of the output. 

In any case, the fact that the current code suggests that you can control exponentiation but you cannot is problematic.

**Comment by leejasme** [comment]
I’ve only ever reported the exponentiated estimates and CI in the ~1 year since I’ve started using crr, not sure if others find the original estimates and CI useful. 
I think it’s good to have that option since  exponentiate = F seems to be default in most cases , I would expect that I need to pass in an exponentiate = T when I’m using tidy.crr

**Comment by ddsjoberg** [comment]
Thank you @leejasme for submitting this fix, and @alexpghayes for reviewing! I wanted to add a few comments to this update.

The default summary function for a crr model returns both the regression coef and the exponentiated version. While it is indeed common to exponentiate the coef to obtain the sub-hazard ratio (just like in Cox regression to get the hazard ratio, or in logistic regression to get the odds ratio), there are many situations when you need the coef and not the hazard ratio, e.g. when there is an interaction and the HR is no longer interpretable. I _strongly_ suggest to keep the default `exponentiate = FALSE` as this is in alignment with the many other linear regression tidiers and likely what users would expect the default behavior to be. Moreover, it is possible to build competing risk regression models using the survival package, and the resulting  tibble from that tidier also defaults to `exponentiate = FALSE`.

Thank you again both!

**Comment by leejasme** [comment]
Hi @alexpghayes , I updated the `new_names` in `ci` to reflect the actual values. The `estimate_exp` is now `estimate` and `estimate_neg_exp` is `estimate_neg`.  Will this work? 
Thanks @ddsjoberg  for helping me with this !

**Comment by ddsjoberg** [comment]
Hey @leejasme! I think @alexpghayes retired from broom dev, and @simonpcouch is now the broom CEO?

**Comment by alexpghayes** [comment]
Simon is now the maintainer :)

**Comment by ddsjoberg** [comment]
Thank you for your service @alexpghayes ! I would think broom is one of the most difficult packages to maintain with the constant changes in the dependencies!

**Comment by leejasme** [comment]
thanks @ddsjoberg , and @alexpghayes for all your work in maintaining this incredibly useful package!

**Comment by simonpcouch** [comment]
Hey yall! Thanks for catching this and the clear explanation. I appreciate your patience on this—in the middle of a move at the moment.

I agree that this is something we should make sure we get right! The `estimate_exp` and `estimate_neg_exp` aren't user-facing, as they're selected off after the `as_tidy_tibble()` step, so I think it's okay to keep that `new_names` argument as is in the current source! I'm on board for the `log(CI)` change, though, so will commit that quickly and merge once checks look okay!

Thanks again, yall.

**Pull request merged**
