### PR TITLE
eflm tidiers Saxena + Pacha

### PR DESCRIPTION
**Pull request by pachadotdev**
# Hi!

Thanks for making a pull request to broom! A few things to keep in mind that will probably help this PR be merged more quickly:  

* Have you documented the change in `NEWS.md`?  yes
* If this is your first time PRing to broom, have you added yourself as a contributor in the `DESCRIPTION`? yes, and Rahul as well
* Have you added any new vocabulary to `inst/WORDLIST`? (New vocabulary will be noted in the R-CMD-check from GitHub Actions.) no need
* Does R-CMD-check pass on GitHub Actions? (Sometimes, checks may not be passing on the main branch already—if that's the case, just try to make sure your changes don't add any additional errors/warnings.) - yes

If your PR fixes a bug, a [reprex](https://github.com/tidyverse/reprex) of the bug would be much appreciated! - does not apply

If your PR adds new tidiers for external model objects, please link to prior attempts to add these tidiers to the model-exporting package, and include a reprex of the new tidiers' functionality! - eflm is not new, but it had the tidiers in the same pkg

If you're having trouble making any of these requests happen, let us know and we can lend a hand! - thanks :) I'll ask if I have problems

### CODE REVIEW

**Comment by simonpcouch** [comment]
Thanks for the PR! 

It sounds like the author(s) of the PR are involved with development of the model-supplying package? If so, it'd be great if you could continue to export these tidiers from that package. If dependencies are a concern, the only dependency you need to take on is {generics}, designed to be a lightweight dependency that only supplies model generics. Some guidance [here](https://www.tidymodels.org/learn/develop/broom/). :-)

**Comment by pachamaltese** [comment]
> Thanks for the PR!
> 
> It sounds like the author(s) of the PR are involved with development of the model-supplying package? If so, it'd be great if you could continue to export these tidiers from that package. If dependencies are a concern, the only dependency you need to take on is {generics}, designed to be a lightweight dependency that only supplies model generics. Some guidance [here](https://www.tidymodels.org/learn/develop/broom/). :-)

hi!
yes, this is a sub-product of my thesis
I sent this PR because of a round problem (a data.frame vs tibble thing), I'm gonna ask my questions about that here

**Comment by pachamaltese** [comment]
the problem I see with tests like this:
```
patrick::with_parameters_test_that("eglm + broom is the same as glm:", {
  m1 <- glm(model, family = family, data = mtcars)
  m2 <- eglm(model, family = family, data = mtcars, reduce = reduce)

  tm1 <- broom::tidy(m1, conf.int = TRUE, conf.level = 0.9)
  tm2 <- broom::tidy(m2, conf.int = TRUE, conf.level = 0.9)

  am1 <- broom::augment(m1, newdata = mtcars)
  am2 <- broom::augment(m2, newdata = mtcars)

  expect_equal(tm2, tm1)
  expect_equal(am2, am1)
},
.cases = eglm_cases()
)
```

is that testthat doesn't pick MASS, regardless of using generics or S3 in the old way

**Comment by simonpcouch** [comment]
Apologies on the delay!

It's not immediately clear to me whether your question is related to this PR. You may have more success asking your question on RStudio Community. :-)

**Pull request closed without merging**
