### PR TITLE
use travis to build website

### PR DESCRIPTION
**Pull request by IndrajeetPatil**
Next, make sure that a `gh-pages` branch exists. The simplest way to do so is to run the following git commands locally:

```bash
git checkout --orphan gh-pages
git rm -rf .
git commit --allow-empty -m 'Initial gh-pages commit'
git push origin gh-pages
git checkout master
```

We recommend doing this outside of RStudio (with the project closed) as from RStudio's perspective you end up deleting all the files and then re-creating them.

### CODE REVIEW

**Comment by alexpghayes** [comment]
Hey @jimhester can we get a sanity check that this is the right way to set up automatic pkgdown deploys?

**Comment by jimhester** [comment]
I think that seems right, @alexpghayes you will need to run `travis::use_travis_deploy()` from the [travis package](https://github.com/ropenscilabs/travis) to setup the necessary deploy key so you can push to the gh-pages branch to deploy the site.

**Comment by alexpghayes** [comment]
@IndrajeetPatil does the build need to pass for the site to deploy?

**Comment by IndrajeetPatil** [comment]
No, it should deploy even if the build doesn't succeed. 

Only the parts of the `yaml` which are in the `after_success` entry will work after the builds succeed.
https://github.com/tidymodels/broom/blob/ae40a4b92530a1205a5bd56975acecfbe213058a/.travis.yml#L71-L74

**Comment by alexpghayes** [comment]
Any idea why Travis won't build https://travis-ci.org/tidymodels/broom/builds/517607964#L3476? Is this related to what you added or something else?

**Pull request merged**
