### PR TITLE
Update tidier for survival::survdiff

### PR DESCRIPTION
**Pull request by thisisnic**
This change relates to part of #450 

Hope this looks alright - let me know if anything needs updating!

### CODE REVIEW

**Comment by alexpghayes** [comment]
Can you write a short description of what tests weren't passing before and how this change fixes them? Since I haven't used the survival tidiers before I have a hard time understanding the change you made.

**Comment by alexpghayes** [comment]
Would you mind writing an example showing the behavior of the tidier before and after those changes? Still trying to wrap my head around this.

**Comment by thisisnic** [comment]
The bit that I edited was inside `tidy.survdiff()`.  Here's an example call to `survdiff()`:
```
x <- survdiff(Surv(time, status) ~ pat.karno + ph.ecog +
                    strata(inst) + strata(sex), data = lung)
```
The code inside `tidy.survdiff()` that I changed originally looked like this:
```
l <- lapply(strsplit(rownames(x$n), ", "), strsplit, "=")
row_list <- lapply(l, function(x)
  structure(
    as.data.frame(lapply(x, "[", 2), stringsAsFactors = FALSE),
    names = sapply(x, "[", 1)
  ))
gvars <- do.call("rbind", row_list)
```
`gvars` is later combined via `bind_cols` with the model results and is what's causing the test failure due to the column names, as show below:
 
```
head(gvars)
# pat.karno ph.ecog
# 1         30       2
# 2         40       2
# 3         50       2
# 4         60       0
# 5         60       1
# 6         60       2
```

So I updated it to just take the exist values in a column called "..." as below:

```  
gvars = data.frame("..." = rownames(x$n), stringsAsFactors = FALSE)
```
So now it's compliant with possible values in `column_glossary`:
```
head(gvars)
# ...
# 1 pat.karno=30, ph.ecog=2
# 2 pat.karno=40, ph.ecog=2
# 3 pat.karno=50, ph.ecog=2
# 4 pat.karno=60, ph.ecog=0
# 5 pat.karno=60, ph.ecog=1
# 6 pat.karno=60, ph.ecog=2
```

However after reading the discussion on the issue page, I'm now unsure whether it'd be better to stick with the previous implementation and set `strict` to `FALSE` in the tests as I don't think my implementation strictly meets the definition of tidy data?

**Comment by alexpghayes** [comment]
Sorry for the delay in responding here.

Yeah, I think the old behavior had a more tidy output. The issue here is that columns in the original data should be allowed in this case. Let's go with `strict = FALSE` here. Would you be willing to document which strict tests fail and why that's okay?

**Comment by thisisnic** [comment]
Yep, I'll get on it now!

**Pull request closed without merging**
