### PR TITLE
change match.arg to rlang::arg_match

### PR DESCRIPTION
**Pull request by asbates**
Calls to match.arg changed to rlang::arg_match closing #553.

Please bear with me if there is anything else I was supposed to do. This is my first pull request!

### CODE REVIEW

**Comment by asbates** [comment]
Um, sorry but I'm not sure what happened to cause AppVeyor and Travis CI to fail.

Did I do something wrong?

**Comment by IndrajeetPatil** [comment]
I don't think the failure of the build has anything to do with the content of the PR. The builds are failing because one of the examples involving tidier for the lavaan package is failing (#571)-

```r
* checking examples ... ERROR
Running examples in 'broom-Ex.R' failed
The error most likely occurred in:
> base::assign(".ptime", proc.time(), pos = "CheckExEnv")
> ### Name: glance.lavaan
> ### Title: Glance at a(n) lavaan object
> ### Aliases: glance.lavaan
> 
> ### ** Examples
> 
> 
> library(lavaan)
This is lavaan 0.6-3
lavaan is BETA software! Please report any bugs.
> 
> cfa.fit <- cfa(
+   'F =~ x1 + x2 + x3 + x4 + x5',
+   data = HolzingerSwineford1939, group = "school"
+ )
> glance(cfa.fit)
Error in .f(.x[[i]], ...) : object 'rmsea.ci.upper' not found
Calls: glance ... <Anonymous> -> vars_rename_eval -> map_if -> map -> .f
Execution halted
* checking for unstated dependencies in 'tests' ... OK
* checking tests ...
  Running 'test-all.R' [35s]
 ERROR
Running the tests in 'tests/test-all.R' failed.
Last 13 lines of output:
  10: function_list[[k]](value)
  11: rename(., rmsea.conf.high = rmsea.ci.upper, AIC = aic, BIC = bic)
  12: rename.data.frame(., rmsea.conf.high = rmsea.ci.upper, AIC = aic, BIC = bic)
  13: tidyselect::vars_rename(names(.data), !!!quos(...))
  14: vars_rename_eval(quos, .vars)
  15: map_if(quos, is_symbol, eval_tidy, data)
  16: map(.x[sel], .f, ...)
  17: .f(.x[[i]], ...)
  
  == testthat results  ===========================================================
  OK: 2805 SKIPPED: 3 FAILED: 1
  1. Error: glance.lavaan (@test-lavaan.R#47) 
  
  Error: testthat unit tests failed
  Execution halted
```

**Comment by alexpghayes** [comment]
I'll try to take a look at this in a couple days.

**Comment by alexpghayes** [comment]
Oh god sorry this took so long to get around to. Looks great! Will you:

- [ ] Add yourself as a contributor in `DESCRIPTION`
- [ ] Update `NEWS` with a tidbit like: "Uses `rlang::arg_match` for more informative errors on argument mispecification?"

**Comment by alexpghayes** [comment]
Fantastic, thank you! Again, sorry for the delay!

**Pull request merged**
