### PR TITLE
Add lm.beta tidier

### PR DESCRIPTION
**Pull request by mattle24**
TODO before merging

- [x] complete documentation for tidy.lm.beta
- [x] add tests for tidy.lm.beta
- [x] Add as a contributor to DESCRIPTION
- [x] check that code passes conventions with `lintr`
- [x] Update NEWS.md to reflect the changes you’ve made
- [x] check test coverage ✅  
- [x] pass the AppVeyor and Travis CI builds ⚠️

### CODE REVIEW

**Comment by mattle24** [comment]
From issue: https://github.com/tidymodels/broom/issues/496

**Comment by mattle24** [comment]
⚠️ App Veyor failed because does not have `lm.beta` package.

**Comment by alexpghayes** [comment]
It looks like the build failures might clear up if you add `lm.beta` to suggests? You can do this with `usethis::use_package("lm.beta", type = "Suggests")`.

**Comment by mattle24** [comment]
Sounds good, thanks! Added that so hopefully the tests will run more smoothly now. 

What should I do about the tidier returning the column `standardized.estimate`? It's not in the glossary. 
lm_beta_tidy

**Comment by alexpghayes** [comment]
You'll need to add it to the tidy column glossary in https://github.com/alexpghayes/modeltests. The file you'll want to change is https://github.com/alexpghayes/modeltests/blob/master/data-raw/columns_tidy.yaml

I recommending using `std_estimate` instead of `standardized.estimate` for brevity / style.

**Comment by alexpghayes** [comment]
Merged the PR in `modeltests` and am now re-running the tests.

**Comment by mattle24** [comment]
Awesome, thank you!

**Comment by mattle24** [comment]
Sorry, messed up that modeltests PR. I didn't realize I had to run `create_glossaries.R`. Ran that file and opened a [new PR (#16)](https://github.com/alexpghayes/modeltests/pull/16) with the update. All tests pass on my system now for both `test()` and `check()`.

**Comment by alexpghayes** [comment]
Merged! Fantastic work -- thank you!

**Comment by mattle24** [comment]
Thanks for the help Alex! Really excited to be contributing!

**Pull request merged**
