### PR TITLE
Small tidy/glance methods for rma objects from the metafor R package.

### PR DESCRIPTION
**Pull request by talgalili**
This PR adds a tidy/glance method for rma objects, which are the fitted model objects from the metafor package implementing meta-analysis models.

https://github.com/wviechtb/metafor/
https://cran.r-project.org/web/packages/metafor/index.html

(this is my first ever PR to github from outside of github, my apologies upfront if I've missed something important)

### CODE REVIEW

**Comment by talgalili** [comment]
It seems the error is due to a general problem in the branch.

**Comment by alexpghayes** [comment]
Would you mind pulling the most recent version of master? I think this would be a valuable contribution. We should also change the method to return a `tibble` with the standard column names while we're at it.

Related to #103, #204.

**Comment by IndrajeetPatil** [comment]
To be consistent with the rest of the tidiers in `broom` package, shouldn't the tidy dataframe 
```r
tidy.rma <- function(x, ...) {
  with(x,
       data.frame(b = b, se = se, zval = zval, pval = pval, ci.lb = ci.lb, ci.ub = ci.ub))
}
```
have the following column names instead?
```r
tidy.rma <- function(x, ...) {
  with(
    x,
    data.frame(
      estimate = b,
      std.error = se,
      z.value = zval,
      p.value = pval,
      conf.low = ci.lb,
      conf.high = ci.ub
    )
  )
}
```

**Comment by alexpghayes** [comment]
It should. It's been long enough that I'm going to close this and open an issue to make `metafor` tidiers from scratch.

**Pull request closed without merging**
