### PR TITLE
Lint

### PR DESCRIPTION
**Pull request by alexpghayes**
The best time to lint was 5 commits ago. The second best time is now.

### CODE REVIEW

**Comment by alexpghayes** [comment]
@IndrajeetPatil Can you link me to some documentation on the linting? IIRC you set that up, and I'm struggling to remember how it works. In particular, I love to know:

- where I set the linting rules
- how to lint locally on my computer
- how to tell the linter to ignore certain linting violations

**Comment by IndrajeetPatil** [comment]
@alexpghayes Here are responses to your specific questions:

- You set up the linting rules in your Debian control file  (https://github.com/tidymodels/broom/blob/master/.lintr)
- You can run `lintr` locally using `lintr::lint_package()`, but I personally prefer `goodpractice::gp()` which gives you a much thorough log of best practices and lints are one of them
- You can turn off certain lints by setting them to `NULL`. For example, the typical recommendation is that your margin column shouldn't exceed 80 in a single line and I find it too stringent, so I instead use `line_length_linter(100)` and change bunch of other things:
https://github.com/IndrajeetPatil/ggstatsplot/blob/master/.lintr

The best documentation for this is just the package manual and vignette. I haven't really searched enough though, so maybe there are some other references out there that I don't know about:
https://cran.r-project.org/web/packages/lintr/vignettes/creating_linters.html

**Comment by alexpghayes** [comment]
Thank you!

**Comment by alexpghayes** [comment]
Closing for now because it'll cause a lot of merge conflict with existing PRs. This can happen at some point down the line when I'm caught up on PRs.

**Pull request closed without merging**
