### PR TITLE
adding mlm tidier

### PR DESCRIPTION
**Pull request by shabbybanks**
Fixing #221 : 
  * adding confidence interval for `mlm` object.
  * quick tidy for `mlm` object inserted into `lm` tidier.
  * adding basic tests.

### CODE REVIEW

**Comment by shabbybanks** [comment]
I noticed that the tests I added do not hit the confidence interval code. I will patch the PR.

**Comment by shabbybanks** [comment]
And now there are these awful CRAN warnings:
```
Unexported object imported by a ':::' call: 'stats:::format.perc'
  See the note in ?`:::` about the use of this operator.
  Including base/recommended package(s):
  'stats'
```
Not sure what your approach is on that one. (TBH, `confint.mlm` should just belong to `stats`, which I would submit a PR for, but I don't think it is on github, and I am not going to deal with `r-dev`.)

**Comment by shabbybanks** [comment]
OK, duh, the unexported function was a one-liner, and I just pasted it in.

**Comment by alexpghayes** [comment]
Fantastic. Will you add yourself as a contributor in `DESCRIPTION` and then I'll merge?

**Pull request merged**
