### PR TITLE
Allow user to specify confidence level in `tidy.rma`

### LINKED ISSUE #1041: `conf.level` has no effect on rma objects
## The problem

I'm trying to return a confidence interval other that 95% from a metafor object. `broom` has the argument `conf.level`  which the docs state should return a different value for conf.high/low. Instead the argument seems to be ignored.

## Reproducible example

This is the example from the docs, but with the `conf.int` and `conf.level` arguments specified.

``` r
library(metafor)
#> Loading required package: Matrix
#> 
#> Loading the 'metafor' package (version 3.0-2). For an
#> introduction to the package please type: help(metafor)
library(broom)

df <-
  escalc(
    measure = "RR",
    ai = tpos,
    bi = tneg,
    ci = cpos,
    di = cneg,
    data = dat.bcg
  )

meta_analysis <- rma(yi, vi, data = df, method = "EB")

# These are the defaults
tidy(meta_analysis, conf.int=TRUE, conf.level = 0.95)
#> # A tibble: 1 x 8
#>   term    type    estimate std.error statistic   p.value conf.low conf.high
#>   <chr>   <chr>      <dbl>     <dbl>     <dbl>     <dbl>    <dbl>     <dbl>
#> 1 overall summary   -0.715     0.181     -3.95 0.0000774    -1.07    -0.360
# But 99% doesn't work
tidy(meta_analysis, conf.int=TRUE, conf.level = 0.99)
#> # A tibble: 1 x 8
#>   term    type    estimate std.error statistic   p.value conf.low conf.high
#>   <chr>   <chr>      <dbl>     <dbl>     <dbl>     <dbl>    <dbl>     <dbl>
#> 1 overall summary   -0.715     0.181     -3.95 0.0000774    -1.07    -0.360
# And neither does 90%
tidy(meta_analysis, conf.int=TRUE, conf.level = 0.90)
#> # A tibble: 1 x 8
#>   term    type    estimate std.error statistic   p.value conf.low conf.high
#>   <chr>   <chr>      <dbl>     <dbl>     <dbl>     <dbl>    <dbl>     <dbl>
#> 1 overall summary   -0.715     0.181     -3.95 0.0000774    -1.07    -0.360
```

<sup>Created on 2021-08-17 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

### PR DESCRIPTION
**Pull request by tarensanders**
This fixes #1041 in which the argument `conf.level` is available and documented, but has no effect on the overall estimate. It uses the exact same method as `metafor` for calculating the confidence interval, to prevent mismatched CIs (from [here](https://github.com/wviechtb/metafor/blob/749687fc2b8193edfb9fc7f0b1e931eceb1b0318/R/rma.uni.r#L2131)).

I am still fairly new to GitHub, so please let me know if there's any additional changes required.

Thanks for making a pull request to broom! A few things to keep in mind that will probably help this PR be merged more quickly:  

* [x] Have you documented the change in `NEWS.md`?  
* [x] If this is your first time PRing to broom, have you added yourself as a contributor in the `DESCRIPTION`?
* Have you added any new vocabulary to `inst/WORDLIST`? (New vocabulary will be noted in the R-CMD-check from GitHub Actions.) **N/A**
* [ ] Does R-CMD-check pass on GitHub Actions? (Sometimes, checks may not be passing on the main branch already—if that's the case, just try to make sure your changes don't add any additional errors/warnings.) 
* Have you updated `DESCRIPTION` if your feature/bug fix requires a specific version of a package? **N/A**
* Have you added unit tests for any new functionality? **N/A**

### CODE REVIEW

**Comment by simonpcouch** [comment]
This looks great, much appreciated! No edits to your existing proposed changes, but could you add unit testing to ensure that 

* the confidence intervals are now sensitive to this argument (i.e. the values do change when `level` does) and that 
* the newly supplied CIs are equal to those supplied by {rma} when `level` matches? The `tolerance` argument to `testthat::expect_equal` maybe be helpful here :-)

Happy to merge with those changes, or to take over if you're having trouble making that unit testing happen.

Thanks again!

**Comment by simonpcouch** [comment]
Feel free to ignore the failing checks related to `survival`!

**Comment by tarensanders** [comment]
Done! The failing tests on my machine are all unrelated to the changes.

**Comment by simonpcouch** [comment]
Wonderful, thank you! Will take a look at checks once they're done running and merge if nothing new. Thank you for your patience. :-)

**Pull request merged**
