### PR TITLE
new tidiers: vars package / varest objects

### PR DESCRIPTION
**Pull request by vincentarelbundock**
The goal of this PR is to address issue #161. It is marked as WIP because I have a couple questions a few notes.

Questions:

* The `vars` package does not define a `confint` method and does not report confidence intervals. Should the `tidy` method (a) include and document a `conf.int` argument and print an informative error if users set it to `TRUE`, or (b) exclude this argument from the function definition?
* One important information to report in `glance` is the lag order. Right now, I included a column called "order". Is that a good name? Should I make a PR to `modeltests`?

Note:

* `varest` objects include results for several levels. These are indicated in a `group` column produced by `tidy`.
* It is not clear to me what should be included in the `augment` output from a VAR model. For now, I do not define this function, but that might be something to consider in the future if an expert can help.
*  Right now, the `glance` test is commented out until `modeltests` includes and documents the column name.

### CODE REVIEW

**Comment by simonpcouch** [comment]
As for your first bullet point, it's fine to exclude the `conf.*` level arguments and document the behavior in `@details`. :-)

Generally, when it comes to modeltests, feel free to file a PR there with the entries you need and link here. I'll merge there and broom can temporarily depend on the `Remotes:` version of modeltests until we push a release out to CRAN!

It's fine to not define an `augment` method, feel free to uncomment the `glance` method once the modeltests PR is merged.

**Comment by vincentarelbundock** [comment]
Thanks for the info. 

I think there's an argument to be made for *including* `conf.*` and exiting with an error instead of sinking it in `...`. This would be more explicit, which I prefer, but I'm not dogmatic enough to argue if you prefer I remove the argument and mention this in docs.

**Comment by simonpcouch** [comment]
I'm on board for a warning in that case!

**Comment by vincentarelbundock** [comment]
Removing the [WIP] tag because I think this looks pretty good now. The remaining error should be fixed when `modeltests` is updated by this PR: https://github.com/alexpghayes/modeltests/pull/35

```r
== Failed tests ================================================================
-- Failure (test-vars.R:29:3): glance.vars -------------------------------------
length(unacceptable) == 0 is not TRUE

`actual`:   FALSE
`expected`: TRUE 
Output column names not in the column glossary: lag.order

[ FAIL 1 | WARN 25 | SKIP 3 | PASS 3886 ]
Error: Error: Test failures
Execution halted
```

**Comment by simonpcouch** [comment]
Much appreciated! :-)

**Comment by vincentarelbundock** [comment]
Ooof, this one wasn’t so clean. Thanks for the review!

**Pull request merged**
