### PR TITLE
Zootidier

### LINKED ISSUE #915: tidy.zoo no longer works on univariate zoo series
Please briefly describe your problem and what output you expect. If you have a question, please don't use this form. Instead, ask on <https://stackoverflow.com/> or <https://community.rstudio.com/>.

Previously (broom 0.5.X) tidy.zoo() would convert a univariate zoo series (essentially a ts series) to a tibble without problem. In broom 0.7.0 this no longer works, which is not documented and not indicated in the changes

Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](http://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

---

Brief description of the problem
Following the broom tidy.zoo example, but using a univariate series. tidy.zoo now throws an error
Workaround is to convert to a tibble manually

```r
library(zoo)
library(ggplot2)

set.seed(1071)

# data generated as shown in the zoo vignette
Z.index <- as.Date(sample(12450:12500, 10))
Z.data <- rnorm(30) # univariate series
Z <- zoo(Z.data, Z.index)

tidy(Z)
# throws an error , can't find column

# works fine in the multivariate example
# data generated as shown in the zoo vignette
Z.index <- as.Date(sample(12450:12500, 10))
Z.data <- matrix(rnorm(30), ncol = 3)
colnames(Z.data) <- c("Aa", "Bb", "Cc")
Z <- zoo(Z.data, Z.index)

tidy(Z)

```
> version
               _                           
platform       x86_64-w64-mingw32          
arch           x86_64                      
os             mingw32                     
system         x86_64, mingw32             
status                                     
major          4                           
minor          0.1                         
year           2020                        
month          06                          
day            06                          
svn rev        78648                       
language       R                           
version.string R version 4.0.1 (2020-06-06)
nickname       See Things Now   
> packageVersion("broom")
[1] ‘0.7.0’

### PR DESCRIPTION
**Pull request by WillemVervoort**
# Hi!

Thanks for making a pull request to broom! A few things to keep in mind that will probably help this PR be merged more quickly:  

* Have you documented the change in `NEWS.md`?  yes
* If this is your first time PRing to broom, have you added yourself as a contributor in the `DESCRIPTION`? yes
* Have you added any new vocabulary to `inst/WORDLIST`? (New vocabulary will be noted in the R-CMD-check from GitHub Actions.) NA
* Does R-CMD-check pass on GitHub Actions? (Sometimes, checks may not be passing on the main branch already—if that's the case, just try to make sure your changes don't add any additional errors/warnings.) 
hmm, not sure, I think so

If your PR fixes a bug, a [reprex](https://github.com/tidyverse/reprex) of the bug would be much appreciated!

Fixes #915 

[BroomTestResult.txt](https://github.com/tidymodels/broom/files/5116237/BroomTestResult.txt)

If your PR adds new tidiers for external model objects, please link to prior attempts to add these tidiers to the model-exporting package, and include a reprex of the new tidiers' functionality!

If you're having trouble making any of these requests happen, let us know and we can lend a hand!

### CODE REVIEW

**Comment by simonpcouch** [comment]
Thanks for the PR! It looks like, as is, it deletes the return values of many docs entries. Could you ensure that only relevant documentation is adjusted?

**Comment by WillemVervoort** [comment]
@simonpcouch  I noticed that too, sorry for my ignorance. Is this because I ran devtools::install  and devtools::check on the local repos and pushed afterwards? I am just trying to figure out why that happened as I did not really change anything there.

**Comment by simonpcouch** [comment]
No worries at all! I'd assume it's because of dependency version mismatch with modeltests, devtools, or roxygen2. Maybe start with updating those and re`document()`ing to see if those changes are resolved. `remotes::install_deps()` might be another useful tool, too. :-)

**Comment by WillemVervoort** [comment]
OK, I am struggling here, I thought this would be fairly easy, maybe I should delete the PR. devtools::check() on my local repos give a ton of warnings about non-installed packages even though remotes::install_deps() on the local repos does not install anything. Are all all the dependencies listed?

For example:
Warning: [C:\Users\rver4657\Documents\broom\R\mfx-tidiers.R:130] @seealso Link to unavailable package: mfx::poissonmfx. there is no package called ‘mfx’
Warning: [C:\Users\rver4657\Documents\broom\R\mfx-tidiers.R:130] @seealso Link to unavailable package: mfx::probitmfx. there is no package called ‘mfx’
Warning: [C:\Users\rver4657\Documents\broom\R\mfx-tidiers.R:186] @seealso Link to unavailable package: mfx::logitmfx. there is no package called ‘mfx’
Warning: [C:\Users\rver4657\Documents\broom\R\mfx-tidiers.R:186] @seealso Link to unavailable package: mfx::negbinmfx. there is no package called ‘mfx’
Warning: [C:\Users\rver4657\Documents\broom\R\mfx-tidiers.R:186] @seealso Link to unavailable package: mfx::poissonmfx. there is no package called ‘mfx’
Warning: [C:\Users\rver4657\Documents\broom\R\mfx-tidiers.R:186] @seealso Link to unavailable package: mfx::probitmfx. there is no package called ‘mfx’
Warning: [C:\Users\rver4657\Documents\broom\R\mfx-tidiers.R:257] @seealso Link to unavailable package: mfx::betamfx. there is no package called ‘mfx’
Warning: [C:\Users\rver4657\Documents\broom\R\mfx-tidiers.R:268] @param Link to unavailable package: betareg::predict.betareg. there is no package called ‘betareg’
Warning: [C:\Users\rver4657\Documents\broom\R\mfx-tidiers.R:271] @param Link to unavailable package: betareg::residuals.betareg. there is no package called ‘betareg’
Warning: [C:\Users\rver4657\Documents\broom\R\mfx-tidiers.R:276] @details Link to unavailable package: mfx::betamfx. there is no package called ‘mfx’
Warning: [C:\Users\rver4657\Documents\broom\R\mfx-tidiers.R:279] @seealso Link to unavailable package: mfx::betamfx. there is no package called ‘mfx’
Warning: [C:\Users\rver4657\Documents\broom\R\mfx-tidiers.R:311] @details Link to unavailable package: mfx::betamfx. there is no package called ‘mfx’
Warning: [C:\Users\rver4657\Documents\broom\R\mfx-tidiers.R:313] @seealso Link to unavailable package: mfx::betamfx. there is no package called ‘mfx’
Warning: [C:\Users\rver4657\Documents\broom\R\mlogit-tidiers.R:6] @param Link to unavailable package: mlogit::mlogit. there is no package called ‘mlogit’
Warning: [C:\Users\rver4657\Documents\broom\R\mlogit-tidiers.R:27] @seealso Link to unavailable package: mlogit::mlogit. there is no package called ‘mlogit’
Warning: [C:\Users\rver4657\Documents\broom\R\mlogit-tidiers.R:106] @seealso Link to unavailable package: mlogit::mlogit. there is no package called ‘mlogit’
Warning: [C:\Users\rver4657\Documents\broom\R\muhaz-tidiers.R:4] @param Link to unavailable package: muhaz::muhaz. there is no package called ‘muhaz’

And many many more. Sorry happy to close the PR and I can send you the code for zootidier and maybe it is easier from your end.

**Comment by WillemVervoort** [comment]
> packageVersion("devtools")
[1] ‘2.3.1’
> packageVersion("roxygen2")
[1] ‘7.1.1’
> packageVersion("modeltests")
[1] ‘0.1.2’
> packageVersion("testthat")
[1] ‘2.3.2’

**Comment by simonpcouch** [comment]
Looks like quite a few of them are fixed! Thanks to putting some time in to that.

There are some stray package version mismatches that are resulting in documentation "links" pointing to new help-pages. These kinds of inconsistencies are due to a change from a few months ago in the way that help-files link to each other, and have been a pain for R developers generally—nothing that's your fault. :-)

I'm going to go ahead and commit your important changes myself, with some small edits, and close this PR. Thank you for contributing!

**Pull request closed without merging**
