### PR TITLE
Add summary.lm tidiers

### PR DESCRIPTION
**Pull request by grantmcdermott**
Adds `tidy` and `glance` methods for `summary.lm` objects.

    devtools::load_all('~/Documents/Projects/broom') ## load my dev version
    #> Loading broom

    m = lm(mpg ~ wt * disp, mtcars)
    s = summary(m)

    ## compare tidy

    tidy(m, conf.int = TRUE)
    #> # A tibble: 4 x 7
    #>   term        estimate std.error statistic  p.value conf.low conf.high
    #>   <chr>          <dbl>     <dbl>     <dbl>    <dbl>    <dbl>     <dbl>
    #> 1 (Intercept)  44.1      3.12        14.1  2.96e-14 37.7       50.5   
    #> 2 wt           -6.50     1.31        -4.95 3.22e- 5 -9.19      -3.81  
    #> 3 disp         -0.0564   0.0132      -4.26 2.10e- 4 -0.0835    -0.0292
    #> 4 wt:disp       0.0117   0.00326      3.60 1.23e- 3  0.00504    0.0184

    tidy(s, conf.int = TRUE)
    #> # A tibble: 4 x 7
    #>   term        estimate std.error statistic  p.value conf.low conf.high
    #>   <chr>          <dbl>     <dbl>     <dbl>    <dbl>    <dbl>     <dbl>
    #> 1 (Intercept)  44.1      3.12        14.1  2.96e-14 37.7       50.5   
    #> 2 wt           -6.50     1.31        -4.95 3.22e- 5 -9.19      -3.81  
    #> 3 disp         -0.0564   0.0132      -4.26 2.10e- 4 -0.0835    -0.0292
    #> 4 wt:disp       0.0117   0.00326      3.60 1.23e- 3  0.00504    0.0184

    ## compare glance (lose some info, but not too bad)

    glance(m)
    #> # A tibble: 1 x 12
    #>   r.squared adj.r.squared sigma statistic  p.value    df logLik   AIC   BIC
    #>       <dbl>         <dbl> <dbl>     <dbl>    <dbl> <dbl>  <dbl> <dbl> <dbl>
    #> 1     0.850         0.834  2.45      52.9 1.16e-11     3  -72.0  154.  161.
    #> # … with 3 more variables: deviance <dbl>, df.residual <int>, nobs <int>

    glance(s)
    #> # A tibble: 1 x 8
    #>   r.squared adj.r.squared sigma statistic  p.value    df df.residual  nobs
    #>       <dbl>         <dbl> <dbl>     <dbl>    <dbl> <dbl>       <int> <dbl>
    #> 1     0.850         0.834  2.45      52.9 1.16e-11     3          28    32

I think the use cases are obvious enough. But the particular one that motivated this PR is where you've estimated a really large model (or group of models) and don't want it (or them) sitting around hogging memory. Now you can convert to the light footprint of a summary.lm object and still retain the ability to tidy. Similarly for downstream packages that rely on **broom**; e.g. **modelsummary** for creating regression tables of a bunch of large models.

    library(modelsummary)

    msummary(list(m, s), output = 'markdown')

<table>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: center;">Model 1</th>
<th style="text-align: center;">Model 2</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: center;">44.082</td>
<td style="text-align: center;">44.082</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">(3.123)</td>
<td style="text-align: center;">(3.123)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">wt</td>
<td style="text-align: center;">-6.496</td>
<td style="text-align: center;">-6.496</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">(1.313)</td>
<td style="text-align: center;">(1.313)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">disp</td>
<td style="text-align: center;">-0.056</td>
<td style="text-align: center;">-0.056</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">(0.013)</td>
<td style="text-align: center;">(0.013)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">wt × disp</td>
<td style="text-align: center;">0.012</td>
<td style="text-align: center;">0.012</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">(0.003)</td>
<td style="text-align: center;">(0.003)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Num.Obs.</td>
<td style="text-align: center;">32</td>
<td style="text-align: center;">32</td>
</tr>
<tr class="even">
<td style="text-align: left;">R2</td>
<td style="text-align: center;">0.850</td>
<td style="text-align: center;">0.850</td>
</tr>
<tr class="odd">
<td style="text-align: left;">R2 Adj.</td>
<td style="text-align: center;">0.834</td>
<td style="text-align: center;">0.834</td>
</tr>
<tr class="even">
<td style="text-align: left;">AIC</td>
<td style="text-align: center;">154.0</td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">BIC</td>
<td style="text-align: center;">161.3</td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Log.Lik.</td>
<td style="text-align: center;">-72.009</td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">F</td>
<td style="text-align: center;">52.947</td>
<td style="text-align: center;"></td>
</tr>
</tbody>
</table>

<sup>Created on 2020-10-29 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

### CODE REVIEW

**Comment by simonpcouch** [comment]
Thanks for the PR!

In [0.7.0](https://github.com/tidymodels/broom/blob/c0ae258b2648628e9e5b2058c27cbe4ffb70dec5/NEWS.md#big-picture-changes) (second bullet point), we decided to move away from supporting `summary.*` objects. Will give Alex a chance to give a look at this before closing!

**Comment by grantmcdermott** [comment]
Ah, bummer. I missed that. 

Sounds like you guys have already had this discussion internally, but any capstone reason? 

I'll state FTR that not having to drag around large model objects is a subject that comes up fairly often in my circles ([example](https://mobile.twitter.com/nickchk/status/1321902374768660480)), but your call obviously.

**Comment by alexpghayes** [comment]
The reason was that I refactored `tidy.lm()` and didn't have the energy to
do the `summary()` objects at the same time. I'm open to adding these back
into but think it's probably best to keep the code for the `lm` and
`summary.lm` objects totally separate (I haven't looked at this PR just
yet) and then maybe test for equality of results?

The reason to keep the code totally separate is that people copy-paste the
`lm` tidiers when implementing new tidiers and we want a super clean
implementation with no extra code -- otherwise that extra code gets
copy-pasted and eventually nobody knows if it's necessary any more!

**Comment by alexpghayes** [comment]
A related question is whether or not we should support `butcher`-ed `lm` objects.

**Comment by simonpcouch** [comment]
Was going to mention [butcher](https://github.com/tidymodels/butcher) as well! Do the tidiers work fine in your use case after butchering?

**Comment by grantmcdermott** [comment]
> I'm open to adding these back into but think it's probably best to keep the code for the `lm` and `summary.lm` objects totally separate (I haven't looked at this PR just yet) and then maybe test for equality of results?

Cool. I'm happy to move them to separate script and test files. 

Meta question:

Would you like a single `summary-tidiers.R` file where people can add summary methods for other model classes too (`summary.glm`, etc.)? Or, do you want a standalone `summary-lm-tidiers.R` file?

**Comment by grantmcdermott** [comment]
>  Do the tidiers work fine in your use case after butchering?

I think they do generally work well for "butchered" `lm` objects, although I don't have a specific use-case to test rn. 

(I was motivated to add the summary.lm tidiers after someone mentioned they weren't working. Mind you, I'd missed the 0.7.0 memo!)

**Comment by alexpghayes** [comment]
> Would you like a single summary-tidiers.R file where people can add summary methods for other model classes too (summary.glm, etc.)? Or, do you want a standalone summary-lm-tidiers.R file?

The file naming strategy at the moment is `{package}-{object}-tidiers.R`, so `stats-summary-lm-tidiers.R` for consistency.

**Comment by alexpghayes** [comment]
Thank you for the high quality work and patience, as always.

**Pull request merged**
