### PR TITLE
add tidy.epi.2by2() method (issue #711)

### PR DESCRIPTION
**Pull request by nt-williams**
This PR adds a tidier to produce tibbles from objects of class `epi.2by2` from the `epiR` package. I'm not a developer of that package.

Following contributor guidelines: 

- [x] tests were added and the method has 100% coverage
- [x] this PR does not introduce any WARNINGS, ERRORS, or NOTES
- [x] method is documented
- [x] NEWS.md has been updated
- [x] I added myself as a contributor

The method has one additional argument, `parameters`, which specifies whether a tibble containing measures of association, `moa`, and their corresponding CIs should be returned or if test statistics, `stat`, should be. 

An example of functionality: 
``` r
library(broom)
library(epiR)
#> Loading required package: survival
#> Package epiR 1.0-2 is loaded
#> Type help(epi.about) for summary information
#> 

dat <- matrix(c(13,2163,5,3349), nrow = 2, byrow = TRUE)
rownames(dat) <- c("DF+", "DF-")
colnames(dat) <- c("FUS+", "FUS-")
fit <- epi.2by2(dat = as.table(dat), method = "cross.sectional", 
                conf.level = 0.95, units = 100, outcome = "as.columns")

tidy(fit, parameters = "moa")
#> # A tibble: 12 x 4
#>    parameter           estimate conf.low conf.high
#>    <chr>                  <dbl>    <dbl>     <dbl>
#>  1 PR.strata.wald         4.01    1.43      11.2  
#>  2 PR.strata.score        4.01    1.49      10.8  
#>  3 OR.strata.wald         4.03    1.43      11.3  
#>  4 OR.strata.score        4.03    1.49      10.9  
#>  5 OR.strata.cfield       4.03    1.47      12.6  
#>  6 OR.strata.mle          4.02    1.34      14.4  
#>  7 ARisk.strata.wald      0.448   0.0992     0.797
#>  8 ARisk.strata.score     0.448   0.142      0.882
#>  9 PARisk.strata.wald     0.176  -0.0225     0.375
#> 10 PARisk.strata.piri     0.176   0.0389     0.314
#> 11 AFRisk.strata.wald     0.750   0.301      0.911
#> 12 PAFRisk.strata.wald    0.542   0.0361     0.782
tidy(fit, parameters = "stat")
#> # A tibble: 1 x 4
#>   parameter    statistic    df p.value
#>   <chr>            <dbl> <dbl>   <dbl>
#> 1 chisq.strata      8.18     1 0.00424
```

<sup>Created on 2019-06-14 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

### CODE REVIEW

**Comment by alexpghayes** [comment]
This is fantastic. Thank you!

**Comment by nt-williams** [comment]
Glad I could help!

**Comment by IndrajeetPatil** [comment]
To be consistent with the other tidiers in `broom`, shouldn't the `parameter` column in the output dataframe be called `term` instead?

**Comment by alexpghayes** [comment]
It should. In the future will you open an issue? Comments on merged/closed pull requests might disappear if I don't check my email close enough.

**Pull request merged**
