### PR TITLE
coftest: add argument conf.int following discussion #663

### PR DESCRIPTION
**Pull request by MatthieuStigler**
Following on the discussion for issue #663, I added the argument `conf.int` to coeftest.

Please review the PR carefully:

- I did not update the man page
- I did only limited test, as not all packages available
- I am not sure if I did correctly with `return_tidy(regression = TRUE)` ?

Thanks!

### CODE REVIEW

**Comment by IndrajeetPatil** [comment]
@alexpghayes Running `styler::style_pkg()` should remove a number of these lints.

**Comment by MatthieuStigler** [comment]
@IndrajeetPatil Yes I don't understand this well... did I introduce these issues with one of my merge commits? Sorry! Should I try to 1) remove problematic merge commit from queue 2) reset my repo 3) You cherry-pick? 4) Run the lines you mentioned?

Thanks!

**Comment by IndrajeetPatil** [comment]
@MatthieuStigler No, no. You didn't introduce them, they have always been there but now they are visible because all builds are succeeding on Travis and so the lints have become visible. 

I think it will be best for Alex to run this because it will change a massive number of files and there can be merge conflicts.

**Comment by alexpghayes** [comment]
Please ignore the style comments for now! I will run styler on the whole package in a bit and then you should be able to merge in master after that!

**Pull request merged**
