### PR TITLE
Margins tidiers

### LINKED ISSUE #700: Add tidiers for margins and mfx objects
It would be great to have tidy methods for objects from the [**margins**](https://github.com/leeper/margins) and [**mfx**](https://cran.r-project.org/web/packages/mfx/index.html) packages. 

Among other things, this would go a long way towards improving the table support for generalized linear models like logit and probit regressions, where you often want to report actual marginal effects rather than the naive coefficient values. (I'm thinking of the fact that modern table-exporting packages like [huxtable](https://github.com/hughjonesd/huxtable) and [gtsummary](https://github.com/vincentarelbundock/gtsummary) rely on `broom::tidy()` as a first step.) AFAIK, there is currently no fully automated way to produce, say, a LaTeX table of marginal effects from a logistic regression in R.

A potential point of convenience here is that `margins` and `mfx` both produce output that already closely resemble tidied regression output. 

``` r
## Run a logistic regression
log_reg <- glm(am ~ cyl + hp + wt, data = mtcars, family = binomial)

## Tidy (but naive) coefficient values
library(broom)
tidy(log_reg)
#> # A tibble: 4 x 5
#>   term        estimate std.error statistic p.value
#>   <chr>          <dbl>     <dbl>     <dbl>   <dbl>
#> 1 (Intercept)  19.7       8.12       2.43   0.0152
#> 2 cyl           0.488     1.07       0.455  0.649 
#> 3 hp            0.0326    0.0189     1.73   0.0840
#> 4 wt           -9.15      4.15      -2.20   0.0276

## Get the actual marginal effects instead

## Option 1: margins package
library(margins, quietly = T)
summary(margins(log_reg))
#>  factor     AME     SE       z      p   lower   upper
#>     cyl  0.0215 0.0470  0.4567 0.6479 -0.0706  0.1135
#>      hp  0.0014 0.0006  2.3197 0.0204  0.0002  0.0026
#>      wt -0.4025 0.1154 -3.4880 0.0005 -0.6287 -0.1764

## Option 2: mfx package
library(mfx, quietly = T, warn.conflicts = F)
logitmfx(log_reg, atmean = F, data = mtcars)
#> Call:
#> logitmfx(formula = log_reg, data = mtcars, atmean = F)
#> 
#> Marginal Effects:
#>          dF/dx  Std. Err.       z  P>|z|
#> cyl  0.0214528  0.0499376  0.4296 0.6675
#> hp   0.0014339  0.0014602  0.9820 0.3261
#> wt  -0.4025475  0.3782646 -1.0642 0.2872
```

<sup>Created on 2019-05-02 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

### PR DESCRIPTION
**Pull request by grantmcdermott**
Closes #700 

Note: I've added an augment method even though it requires rerunning the underlying model, so that other downstream packages (e.g. modelsummary or huxtable) can construct regression tables from margins objects.

### CODE REVIEW

**Comment by grantmcdermott** [comment]
@simonpcouch Sorry for the recurrent updates, but I think we're good to go now. Like my other recent PR (#908), I think we're just waiting on **broom** to recognise the updated glossary terms over at @alexpghayes's modeltests repo (which have [been](https://github.com/alexpghayes/modeltests/pull/32) [merged](https://github.com/alexpghayes/modeltests/pull/33) AFAICT... but may need to to be rebuilt?)

Let me know if you need anything more on my side. For example, I haven't committed the locally-built docs but I would have thought GH Actions will take care of all that...

PS. Here are two simple examples of this PR's functionality in action, taken from the docs.

``` r
devtools::load_all('~/Documents/Projects/broom/')
#> Loading broom

library(margins)

## Example 1: Logit model ##

mod_log <- glm(am ~ cyl + hp + wt, data = mtcars, family = binomial)
# Get tidied "naive" model coefficients
tidy(mod_log)
#> # A tibble: 4 x 5
#>   term        estimate std.error statistic p.value
#>   <chr>          <dbl>     <dbl>     <dbl>   <dbl>
#> 1 (Intercept)  19.7       8.12       2.43   0.0152
#> 2 cyl           0.488     1.07       0.455  0.649 
#> 3 hp            0.0326    0.0189     1.73   0.0840
#> 4 wt           -9.15      4.15      -2.20   0.0276

# Convert to marginal effects with margins::margins()
marg_log <- margins(mod_log)
# Get tidied marginal effects
tidy(marg_log)
#> # A tibble: 3 x 5
#>   term  estimate std.error statistic  p.value
#>   <chr>    <dbl>     <dbl>     <dbl>    <dbl>
#> 1 cyl    0.0215   0.0470       0.457 0.648   
#> 2 hp     0.00143  0.000618     2.32  0.0204  
#> 3 wt    -0.403    0.115       -3.49  0.000487

## Example 2: Threeway interaction terms ##

mod_ie <- lm(mpg ~ wt * cyl * disp, data = mtcars)
# Get tidied "naive" model coefficients
tidy(mod_ie, conf.int = TRUE)
#> # A tibble: 8 x 7
#>   term        estimate std.error statistic  p.value conf.low conf.high
#>   <chr>          <dbl>     <dbl>     <dbl>    <dbl>    <dbl>     <dbl>
#> 1 (Intercept) 108.      23.3          4.62 0.000109  59.6    156.     
#> 2 wt          -24.8      8.47        -2.92 0.00744  -42.3     -7.28   
#> 3 cyl         -10.8      4.34        -2.49 0.0201   -19.8     -1.85   
#> 4 disp         -0.593    0.213       -2.79 0.0102    -1.03    -0.154  
#> 5 wt:cyl        2.91     1.42         2.05 0.0514    -0.0194   5.83   
#> 6 wt:disp       0.184    0.0685       2.69 0.0127     0.0431   0.326  
#> 7 cyl:disp      0.0752   0.0268       2.81 0.00979    0.0199   0.130  
#> 8 wt:cyl:disp  -0.0233   0.00861     -2.71 0.0123    -0.0411  -0.00555

# Convert to marginal effects with margins::margins()
marg_ie0 <- margins(mod_ie)
# Get tidied marginal effects 
tidy(marg_ie0, conf.int = TRUE)
#> # A tibble: 3 x 7
#>   term  estimate std.error statistic p.value conf.low conf.high
#>   <chr>    <dbl>     <dbl>     <dbl>   <dbl>    <dbl>     <dbl>
#> 1 cyl    -3.85      1.46       -2.65 0.00812  -6.71    -1.00   
#> 2 disp   -0.0295    0.0174     -1.70 0.0900   -0.0636   0.00460
#> 3 wt     -2.01      1.17       -1.72 0.0860   -4.30     0.285

# Marginal effects of one interaction variable (here: wt), modulated at 
# specific values of the two other interaction variables (here: cyl and drat)
marg_ie2 <- margins(mod_ie,
                    variables = "wt", ## Main var
                    at = list(cyl = c(4,6,8), drat = c(3, 3.5, 4))) ## Modulating vars
tidy(marg_ie2)
#> # A tibble: 18 x 7
#>    term  at.variable at.value estimate std.error statistic p.value
#>    <chr> <chr>          <dbl>    <dbl>     <dbl>     <dbl>   <dbl>
#>  1 wt    cyl              4       7.91      5.06     1.56    0.118
#>  2 wt    drat             3       7.91      5.06     1.56    0.118
#>  3 wt    cyl              4       7.91      5.06     1.56    0.118
#>  4 wt    drat             3.5     7.91      5.06     1.56    0.118
#>  5 wt    cyl              4       7.91      5.06     1.56    0.118
#>  6 wt    drat             4       7.91      5.06     1.56    0.118
#>  7 wt    cyl              6       2.96      2.52     1.18    0.239
#>  8 wt    drat             3       2.96      2.52     1.18    0.239
#>  9 wt    cyl              6       2.96      2.52     1.18    0.239
#> 10 wt    drat             3.5     2.96      2.52     1.18    0.239
#> 11 wt    cyl              6       2.96      2.52     1.18    0.239
#> 12 wt    drat             4       2.96      2.52     1.18    0.239
#> 13 wt    cyl              8      -1.98      2.40    -0.825   0.409
#> 14 wt    drat             3      -1.98      2.40    -0.825   0.409
#> 15 wt    cyl              8      -1.98      2.40    -0.825   0.409
#> 16 wt    drat             3.5    -1.98      2.40    -0.825   0.409
#> 17 wt    cyl              8      -1.98      2.40    -0.825   0.409
#> 18 wt    drat             4      -1.98      2.40    -0.825   0.409
```

<sup>Created on 2020-08-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by simonpcouch** [comment]
@grantmcdermott This looks really, really great! Thanks for making this happen.

A few small things:

* Use the default method for `augment.margins` so we can be sure that error messages will always be informative ([like here](https://github.com/tidymodels/broom/blob/330b882bb3c59c10ae88c2062e54efba93ebc98f/R/gee.R#L12-L14))
* Wrap any examples that (purposefully) fail with `\dontrun{}` instead of commenting them out (I think there's just one)
* Go ahead and commit the docs—we build/commit them manually on this repo :-)
* Prefix helpers like `contains()` or `all_of()` with an explicit namespace (technically `tidyselect::`, I think, but `dplyr::` is already imported and re-exports them).. this is supported for now, but we generally try to avoid using them without the namespace prefix
* `context("fixest")` should be `context("margins")` at the top of the unit test
* Specify that we'll need dplyr >=1.0.0 in the DESCRIPTION since these use `across()`. It's been a few months now, so I think it's fine to bump that req'd version. :-)

The `modeltests` errors should be fixed now.. I rebuilt the docs a day or two ago!

Thanks again!

**Comment by grantmcdermott** [comment]
Thanks @simonpcouch, will do! Quick question: Shouldn't we also specify tidyr > 1.0.0 in the DESCRIPTION file, since that ensures support for the new `pivot_*` reshape functions?

**Comment by simonpcouch** [comment]
Ah, yes--nice catch!

**Comment by simonpcouch** [comment]
Perfect! Merging! :-)

**Comment by grantmcdermott** [comment]
Super, thanks Simon.

**Pull request merged**
