### PR TITLE
handle 0 weights; closes #232; closes #381

### LINKED ISSUE #232: augment fails for weighted regression with some observations having weight = 0
Reprex in which the first 25 out of 100 observations have weight zero for the regression.

```
library(tidyverse)
library(broom)

n <- 100
set.seed(1)

dumb_data <- data_frame(
    x = 1:n,
    y = 1:n + rnorm(n),
    weights = c(rep(0, n/4), rep(0.5, n/4), rep(1, n/4), rep(1.5, n/4))
)

fit <- lm(y ~ x, data = dumb_data, weights = weights)

fit %>% augment() 
```

```
Error in `$<-.data.frame`(`*tmp*`, ".hat", value = c(0.0409852490954634,  : 
  replacement has 75 rows, data has 100
```
I can trace the error back to this portion of the `augment_columns` code in `utilities.R`:

        infl <- influence0(x, do.coef = FALSE)
        if (!is.null(infl)) {
            if(is_mgcv(x)){
                ret$.hat <- infl
                ret$.sigma <- NA
            }else{
            ret$.hat <- infl$hat
            ret$.sigma <- infl$sigma
            }
        }

`stats::influence` excludes observations with weight = 0, so only 75 observations returned instead of 100 leading to the error. This behavior is documented in `stats::influence`:

> Note that cases with `weights == 0` are *dropped* (contrary to the situation in S).

### LINKED ISSUE #381: `broom::augment` doesn't work if weights are provided for glm
See the reproducible example below. This issue holds only for `stats::glm`, but not for `stats::lm`, for example.

``` r
# loading needed libraries
library(tidyverse)

# for reproducibility
set.seed(200)

# creating dataframes needed for the analysis below
d <- as.data.frame(Titanic)

# creating the model

# lm
x_lm <- stats::lm(formula = mpg ~ wt,
                  weights = disp,
                  data = mtcars)

# glm
x_glm <- stats::glm(
  formula = Survived ~ Sex + Age,
  data = d,
  weights = d$Freq,
  family = "binomial"
)

# checking if broom functions work for lm
broom::tidy(x = x_lm)
#>          term  estimate std.error statistic      p.value
#> 1 (Intercept) 33.061389 1.9836851 16.666651 1.032398e-16
#> 2          wt -4.259288 0.5231535 -8.141565 4.348251e-09

broom::glance(x = x_lm)
#>   r.squared adj.r.squared    sigma statistic      p.value df    logLik
#> 1 0.6884252     0.6780394 42.95647  66.28508 4.348251e-09  2 -80.14204
#>        AIC      BIC deviance df.residual
#> 1 166.2841 170.6813 55357.75          30

head(broom::augment(x = x_lm))
#>           .rownames  mpg    wt X.weights.  .fitted   .se.fit     .resid
#> 1         Mazda RX4 21.0 2.620        160 21.90205 0.7425116 -0.9020536
#> 2     Mazda RX4 Wag 21.0 2.875        160 20.81594 0.6501109  0.1840649
#> 3        Datsun 710 22.8 2.320        108 23.17984 0.8650319 -0.3798401
#> 4    Hornet 4 Drive 21.4 3.215        258 19.36778 0.5535696  2.0322229
#> 5 Hornet Sportabout 18.7 3.440        360 18.40944 0.5141320  0.2905627
#> 6           Valiant 18.1 3.460        225 18.32425 0.5117909 -0.2242515
#>         .hat   .sigma      .cooksd  .std.resid
#> 1 0.04780456 43.63683 1.860008e-03 -0.27220790
#> 2 0.03664695 43.68860 5.800181e-05  0.05522168
#> 3 0.04379564 43.68439 2.022403e-04 -0.09397422
#> 4 0.04284568 43.24929 1.350263e-02  0.77671491
#> 5 0.05156971 43.67817 4.721490e-04  0.13178316
#> 6 0.03193821 43.68621 1.044890e-04 -0.07958780

# checking if broom functions work for glm
broom::tidy(x = x_glm)
#>          term   estimate std.error statistic      p.value
#> 1 (Intercept) -0.7800447 0.2245745 -3.473433 5.138449e-04
#> 2   SexFemale  2.2940067 0.1199432 19.125776 1.540630e-81
#> 3    AgeAdult -0.5564393 0.2276016 -2.444795 1.449345e-02

broom::glance(x = x_glm)
#>   null.deviance df.null    logLik      AIC      BIC deviance df.residual
#> 1      2769.457      23 -1164.547 2335.095 2339.492 2329.095          21

broom::augment(x = x_glm)
#> Error in `$<-.data.frame`(`*tmp*`, ".hat", value = c(`3` = 0.380429990534095, : replacement has 24 rows, data has 32
```

Created on 2018-06-17 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

### PR DESCRIPTION
**Pull request by bfgray3**
I haven't written any tests yet since I wanted to get your preliminary thoughts first.  This solution isn't slick at all and I need you to confirm it's even correct.  Please let me know what you think.

### CODE REVIEW

**Comment by alexpghayes** [comment]
Is the intent here that only columns with non-zero weight get augmented?

**Comment by bfgray3** [comment]
First I check if the model has weights.  Note that even models without weights explicitly passed in the model function call can have them:

``` r
d <- as.data.frame(Titanic)

x_glm <- glm(
  formula = Survived ~ Sex + Age,
  data = d,
  family = "binomial"
)

summary(x_glm$weights)
#>    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
#>    0.25    0.25    0.25    0.25    0.25    0.25
```

Created on 2018-07-17 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

This is why I then also check if all the weights are the same.  As astutely explained in #232, observations with weight 0 are dropped by `influence`.  So I use the names of the influence results to determine which observations have nonzero weight, fill in the relevant values in the data frame, and leave the others (the ones with 0 weight) as 0.  I bet there's a better way to do this.  I also realized that this line is wrong: `nonzero_weight_indices <- as.integer(names(x[["weights"]]))`.  I should be looking for the names of something like `infl$hat`; I can fix this tonight.

``` r
d <- as.data.frame(Titanic)

x_glm <- glm(
  formula = Survived ~ Sex + Age,
  data = d,
  weights = d$Freq,
  family = "binomial"
)

infl <- influence(x_glm)

identical(names(infl$hat), names(infl$sigma))
#> [1] TRUE
all.equal(as.integer(names(infl$hat)), which(x_glm$weights != 0))
#> [1] "names for current but not for target"
```

Created on 2018-07-17 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by bfgray3** [comment]
As a note I'm basing my reprexes off of those in #381.

**Comment by alexpghayes** [comment]
Sorry about the slow reply -- lots of 0.5.0 release stuff happening at the moment. Do you need to check for all the weights being the same, or could you just check for any observations with zero weight?

I also wonder if it makes sense to set `.infl` and `.hat` to `NA` rather than zero for observations given zero weight. My impression is that setting them to zero is slightly better, but we definitely need to document this (`augment.glm` seems like the best place, since that's where the bug is coming from at the moment).

**Comment by bfgray3** [comment]
No worries.  Congratulations on the release.

Good point--we can probably just check for 0 weight.  Later on today I'll make this change, fix the problem I mentioned above, and document this behavior.

**Comment by bfgray3** [comment]
Please let me know if I should change the documentation update (I haven't `devtools::document()`ed it yet).  Also I haven't had time to write the tests yet--sorry for that.  I'll be able to write them over the weekend.  Apologies for the delay.

**Comment by alexpghayes** [comment]
No rush -- thanks for taking this on! I would include the documentation change in the `@return` block. You'll need to add the `@return` tag if there isn't one already.

**Comment by bfgray3** [comment]
I've fixed a bug I had in an earlier version of this PR, added a test, and moved the documentation to a `return` tag.  Please let me know what you think.

**Pull request merged**
