### PR TITLE
Ensure order of terms is not affected by merge inside process_clm

### PR DESCRIPTION
**Pull request by bschneidr**
Addresses issue #420 

When `conf.int = TRUE`, the call to `merge` inside `process_clm` upsets the row-ordering of terms in the `ret` object. These added lines ensure that the original order of terms is preserved.

### CODE REVIEW

**Comment by alexpghayes** [comment]
Looks good. Can you add a short test and include an example of the behavior before/after here in PR thread?

**Comment by bschneidr** [comment]
Gladly! I don't have time at the moment but I'll try to do it tomorrow early in the afternoon.

**Comment by bschneidr** [comment]
The latest commit now includes an additional test inside the set of tests for `tidy.clm`.

Here's the behavior that this pull request fixes. Previously, when `tidy` was called on a model produced by the `clm()` function from the `ordinal` package, the order of terms in the `term` column would vary based on whether `conf.int = TRUE` or `conf.int = FALSE` in the call to `clm()`.

### Old behavior
``` r
library(broom) # Version 0.5.0.9000
library(ordinal) # Version 2018.4-19
fit <- clm(rating ~ temp * contact, data = wine)

tidy_result <- list()
tidy_result$With_Confint <- tidy(fit, conf.int = TRUE)
tidy_result$Without_Confint <- tidy(fit, conf.int = FALSE)

# Note that entries 5 and 6 are 'swapped', depending on whether `conf.int = TRUE`
cbind(With_Confint = tidy_result$With_Confint$term,
      Without_Confint = tidy_result$Without_Confint$term)
#>      With_Confint          Without_Confint      
#> [1,] "1|2"                 "1|2"                
#> [2,] "2|3"                 "2|3"                
#> [3,] "3|4"                 "3|4"                
#> [4,] "4|5"                 "4|5"                
#> [5,] "contactyes"          "tempwarm"           
#> [6,] "tempwarm"            "contactyes"         
#> [7,] "tempwarm:contactyes" "tempwarm:contactyes"
```

### New behavior
With this commit, the order of the terms in the `term` column is the same, regardless of whether `conf.int = TRUE` or `conf.int = FALSE`.
``` r
library(broom)
library(ordinal)
fit <- clm(rating ~ temp * contact, data = wine)

tidy_result <- list()
tidy_result$With_Confint <- tidy(fit, conf.int = TRUE)
tidy_result$Without_Confint <- tidy(fit, conf.int = FALSE)

cbind(With_Confint = tidy_result$With_Confint$term,
      Without_Confint = tidy_result$Without_Confint$term)
#>      With_Confint          Without_Confint      
#> [1,] "1|2"                 "1|2"                
#> [2,] "2|3"                 "2|3"                
#> [3,] "3|4"                 "3|4"                
#> [4,] "4|5"                 "4|5"                
#> [5,] "tempwarm"            "tempwarm"           
#> [6,] "contactyes"          "contactyes"         
#> [7,] "tempwarm:contactyes" "tempwarm:contactyes"
```

**Comment by alexpghayes** [comment]
Awesome! Will you add yourself as a contributor in DESCRIPTION and then I'll merge?

**Comment by bschneidr** [comment]
Happy to do so! This is now part of the most recent commit.

Thanks for making it easy to contribute by adding the 'beginner-friendly' labels to the repo's Issues. Hope this is making it easier to work on a lot of the big picture stuff that's important to `broom`'s future.

**Pull request merged**
